// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/juju/juju/domain/ssh/service (interfaces: ControllerState,ModelState)
//
// Generated by this command:
//
//	mockgen -typed -package service -destination domain/ssh/service/service_mock_test.go github.com/juju/juju/domain/ssh/service ControllerState,ModelState
//

// Package service is a generated GoMock package.
package service

import (
	context "context"
	reflect "reflect"

	machine "github.com/juju/juju/core/machine"
	unit "github.com/juju/juju/core/unit"
	gomock "go.uber.org/mock/gomock"
)

// MockControllerState is a mock of ControllerState interface.
type MockControllerState struct {
	ctrl     *gomock.Controller
	recorder *MockControllerStateMockRecorder
}

// MockControllerStateMockRecorder is the mock recorder for MockControllerState.
type MockControllerStateMockRecorder struct {
	mock *MockControllerState
}

// NewMockControllerState creates a new mock instance.
func NewMockControllerState(ctrl *gomock.Controller) *MockControllerState {
	mock := &MockControllerState{ctrl: ctrl}
	mock.recorder = &MockControllerStateMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockControllerState) EXPECT() *MockControllerStateMockRecorder {
	return m.recorder
}

// GetControllerSSHHostKey mocks base method.
func (m *MockControllerState) GetControllerSSHHostKey(arg0 context.Context) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetControllerSSHHostKey", arg0)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetControllerSSHHostKey indicates an expected call of GetControllerSSHHostKey.
func (mr *MockControllerStateMockRecorder) GetControllerSSHHostKey(arg0 any) *MockControllerStateGetControllerSSHHostKeyCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetControllerSSHHostKey", reflect.TypeOf((*MockControllerState)(nil).GetControllerSSHHostKey), arg0)
	return &MockControllerStateGetControllerSSHHostKeyCall{Call: call}
}

// MockControllerStateGetControllerSSHHostKeyCall wrap *gomock.Call
type MockControllerStateGetControllerSSHHostKeyCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockControllerStateGetControllerSSHHostKeyCall) Return(arg0 string, arg1 error) *MockControllerStateGetControllerSSHHostKeyCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockControllerStateGetControllerSSHHostKeyCall) Do(f func(context.Context) (string, error)) *MockControllerStateGetControllerSSHHostKeyCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockControllerStateGetControllerSSHHostKeyCall) DoAndReturn(f func(context.Context) (string, error)) *MockControllerStateGetControllerSSHHostKeyCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// SetControllerSSHHostKey mocks base method.
func (m *MockControllerState) SetControllerSSHHostKey(arg0 context.Context, arg1 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetControllerSSHHostKey", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetControllerSSHHostKey indicates an expected call of SetControllerSSHHostKey.
func (mr *MockControllerStateMockRecorder) SetControllerSSHHostKey(arg0, arg1 any) *MockControllerStateSetControllerSSHHostKeyCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetControllerSSHHostKey", reflect.TypeOf((*MockControllerState)(nil).SetControllerSSHHostKey), arg0, arg1)
	return &MockControllerStateSetControllerSSHHostKeyCall{Call: call}
}

// MockControllerStateSetControllerSSHHostKeyCall wrap *gomock.Call
type MockControllerStateSetControllerSSHHostKeyCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockControllerStateSetControllerSSHHostKeyCall) Return(arg0 error) *MockControllerStateSetControllerSSHHostKeyCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockControllerStateSetControllerSSHHostKeyCall) Do(f func(context.Context, string) error) *MockControllerStateSetControllerSSHHostKeyCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockControllerStateSetControllerSSHHostKeyCall) DoAndReturn(f func(context.Context, string) error) *MockControllerStateSetControllerSSHHostKeyCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// MockModelState is a mock of ModelState interface.
type MockModelState struct {
	ctrl     *gomock.Controller
	recorder *MockModelStateMockRecorder
}

// MockModelStateMockRecorder is the mock recorder for MockModelState.
type MockModelStateMockRecorder struct {
	mock *MockModelState
}

// NewMockModelState creates a new mock instance.
func NewMockModelState(ctrl *gomock.Controller) *MockModelState {
	mock := &MockModelState{ctrl: ctrl}
	mock.recorder = &MockModelStateMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockModelState) EXPECT() *MockModelStateMockRecorder {
	return m.recorder
}

// GetMachineVirtualSSHHostKey mocks base method.
func (m *MockModelState) GetMachineVirtualSSHHostKey(arg0 context.Context, arg1 machine.UUID) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMachineVirtualSSHHostKey", arg0, arg1)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMachineVirtualSSHHostKey indicates an expected call of GetMachineVirtualSSHHostKey.
func (mr *MockModelStateMockRecorder) GetMachineVirtualSSHHostKey(arg0, arg1 any) *MockModelStateGetMachineVirtualSSHHostKeyCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMachineVirtualSSHHostKey", reflect.TypeOf((*MockModelState)(nil).GetMachineVirtualSSHHostKey), arg0, arg1)
	return &MockModelStateGetMachineVirtualSSHHostKeyCall{Call: call}
}

// MockModelStateGetMachineVirtualSSHHostKeyCall wrap *gomock.Call
type MockModelStateGetMachineVirtualSSHHostKeyCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockModelStateGetMachineVirtualSSHHostKeyCall) Return(arg0 string, arg1 error) *MockModelStateGetMachineVirtualSSHHostKeyCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockModelStateGetMachineVirtualSSHHostKeyCall) Do(f func(context.Context, machine.UUID) (string, error)) *MockModelStateGetMachineVirtualSSHHostKeyCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockModelStateGetMachineVirtualSSHHostKeyCall) DoAndReturn(f func(context.Context, machine.UUID) (string, error)) *MockModelStateGetMachineVirtualSSHHostKeyCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetUnitVirtualSSHHostKey mocks base method.
func (m *MockModelState) GetUnitVirtualSSHHostKey(arg0 context.Context, arg1 unit.UUID) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUnitVirtualSSHHostKey", arg0, arg1)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUnitVirtualSSHHostKey indicates an expected call of GetUnitVirtualSSHHostKey.
func (mr *MockModelStateMockRecorder) GetUnitVirtualSSHHostKey(arg0, arg1 any) *MockModelStateGetUnitVirtualSSHHostKeyCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUnitVirtualSSHHostKey", reflect.TypeOf((*MockModelState)(nil).GetUnitVirtualSSHHostKey), arg0, arg1)
	return &MockModelStateGetUnitVirtualSSHHostKeyCall{Call: call}
}

// MockModelStateGetUnitVirtualSSHHostKeyCall wrap *gomock.Call
type MockModelStateGetUnitVirtualSSHHostKeyCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockModelStateGetUnitVirtualSSHHostKeyCall) Return(arg0 string, arg1 error) *MockModelStateGetUnitVirtualSSHHostKeyCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockModelStateGetUnitVirtualSSHHostKeyCall) Do(f func(context.Context, unit.UUID) (string, error)) *MockModelStateGetUnitVirtualSSHHostKeyCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockModelStateGetUnitVirtualSSHHostKeyCall) DoAndReturn(f func(context.Context, unit.UUID) (string, error)) *MockModelStateGetUnitVirtualSSHHostKeyCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// SetMachineVirtualSSHHostKey mocks base method.
func (m *MockModelState) SetMachineVirtualSSHHostKey(arg0 context.Context, arg1 machine.UUID, arg2 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetMachineVirtualSSHHostKey", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetMachineVirtualSSHHostKey indicates an expected call of SetMachineVirtualSSHHostKey.
func (mr *MockModelStateMockRecorder) SetMachineVirtualSSHHostKey(arg0, arg1, arg2 any) *MockModelStateSetMachineVirtualSSHHostKeyCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetMachineVirtualSSHHostKey", reflect.TypeOf((*MockModelState)(nil).SetMachineVirtualSSHHostKey), arg0, arg1, arg2)
	return &MockModelStateSetMachineVirtualSSHHostKeyCall{Call: call}
}

// MockModelStateSetMachineVirtualSSHHostKeyCall wrap *gomock.Call
type MockModelStateSetMachineVirtualSSHHostKeyCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockModelStateSetMachineVirtualSSHHostKeyCall) Return(arg0 error) *MockModelStateSetMachineVirtualSSHHostKeyCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockModelStateSetMachineVirtualSSHHostKeyCall) Do(f func(context.Context, machine.UUID, string) error) *MockModelStateSetMachineVirtualSSHHostKeyCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockModelStateSetMachineVirtualSSHHostKeyCall) DoAndReturn(f func(context.Context, machine.UUID, string) error) *MockModelStateSetMachineVirtualSSHHostKeyCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// SetUnitVirtualSSHHostKey mocks base method.
func (m *MockModelState) SetUnitVirtualSSHHostKey(arg0 context.Context, arg1 unit.UUID, arg2 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetUnitVirtualSSHHostKey", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetUnitVirtualSSHHostKey indicates an expected call of SetUnitVirtualSSHHostKey.
func (mr *MockModelStateMockRecorder) SetUnitVirtualSSHHostKey(arg0, arg1, arg2 any) *MockModelStateSetUnitVirtualSSHHostKeyCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetUnitVirtualSSHHostKey", reflect.TypeOf((*MockModelState)(nil).SetUnitVirtualSSHHostKey), arg0, arg1, arg2)
	return &MockModelStateSetUnitVirtualSSHHostKeyCall{Call: call}
}

// MockModelStateSetUnitVirtualSSHHostKeyCall wrap *gomock.Call
type MockModelStateSetUnitVirtualSSHHostKeyCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockModelStateSetUnitVirtualSSHHostKeyCall) Return(arg0 error) *MockModelStateSetUnitVirtualSSHHostKeyCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockModelStateSetUnitVirtualSSHHostKeyCall) Do(f func(context.Context, unit.UUID, string) error) *MockModelStateSetUnitVirtualSSHHostKeyCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockModelStateSetUnitVirtualSSHHostKeyCall) DoAndReturn(f func(context.Context, unit.UUID, string) error) *MockModelStateSetUnitVirtualSSHHostKeyCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
